
        
# SQL SERVER
spring:
 datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databasename=seguridad
    username: sa
    password: 12345678
 jpa:
    database: sql-server
    hibernate:
     ddl-auto: update
    show-sql: false
   


server:  port: 8443
  ssl:    key-store: src/main/resources/coders.p12
    key-store-password: coders
    key-store-type: PKCS12
    key-alias: coders 
    